// CustomerBookingBoard
export const FETCHING_BOOKING_LIST = 'FETCHING_BOOKING_LIST'
export const FETCHING_BOOKING_LIST_SUCCESS = 'FETCHING_BOOKING_LIST_SUCCESS'
export const FETCHING_BOOKING_LIST_FAILURE = 'FETCHING_BOOKING_LIST_FAILURE'
export const NO_BOOKING_LIST = 'NO_BOOKING_LIST'
export const FETCHING_ARRIVING_LIST_SUCCESS = 'FETCHING_ARRIVING_LIST_SUCCESS'
export const NO_ARRIVING_LIST = 'NO_ARRIVING_LIST'
export const FETCHING_EATING_LIST_SUCCESS = 'FETCHING_EATING_LIST_SUCCESS'
export const NO_EATING_LIST = 'NO_EATING_LIST'
export const FETCHING_FINISHING_LIST_SUCCESS = 'FETCHING_FINISHING_LIST_SUCCESS'
export const NO_FINISHING_LIST = 'NO_FINISHING_LIST'

export const MOVE_TO_ARRIVING = 'MOVE_TO_ARRIVING'
export const MOVE_TO_EATING = 'MOVE_TO_EATING'
export const MOVE_TO_FINISHING = 'MOVE_TO_FINISHING'

// Restaurant Detail
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT'
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS'
export const FETCHING_RESTAURANT_FAILURE = 'FETCHING_RESTAURANT_FAILURE'
