// CustomerBookingBoard
export const FETCHING_BOOKING_LIST = 'FETCHING_BOOKING_LIST'
export const FETCHING_BOOKING_LIST_SUCCESS = 'FETCHING_BOOKING_LIST_SUCCESS'
export const FETCHING_BOOKING_LIST_FAILURE = 'FETCHING_BOOKING_LIST_FAILURE'
export const NO_BOOKING_LIST = 'NO_BOOKING_LIST'
export const FETCHING_ARRIVING_LIST_SUCCESS = 'FETCHING_ARRIVING_LIST_SUCCESS'
export const NO_ARRIVING_LIST = 'NO_ARRIVING_LIST'
export const FETCHING_EATING_LIST_SUCCESS = 'FETCHING_EATING_LIST_SUCCESS'
export const NO_EATING_LIST = 'NO_EATING_LIST'
export const FETCHING_FINISHING_LIST_SUCCESS = 'FETCHING_FINISHING_LIST_SUCCESS'
export const NO_FINISHING_LIST = 'NO_FINISHING_LIST'
export const FETCHING_WALK_IN_LIST = 'FETCHING_WALK_IN_LIST'
export const FETCHING_WALK_IN_LIST_SUCCESS = 'FETCHING_WALK_IN_LIST_SUCCESS'

export const MOVE_TO_ARRIVING = 'MOVE_TO_ARRIVING'
export const MOVE_TO_EATING = 'MOVE_TO_EATING'
export const MOVE_TO_FINISHING = 'MOVE_TO_FINISHING'

export const SET_BOOKING_DETAIL_STATE = 'SET_BOOKING_DETAIL_STATE'

// Restaurant Detail
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT'
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS'
export const FETCHING_RESTAURANT_FAILURE = 'FETCHING_RESTAURANT_FAILURE'
export const NO_RESTAURNAT_DATA = 'NO_RESTAURNAT_DATA'

// Add Booking
export const INPUT_NAME = 'INPUT_NAME'
export const INPUT_PHONE_NUMBER = 'INPUT_PHONE_NUMBER'
export const INPUT_TIME = 'INPUT_TIME'
export const INPUT_NUM_OF_CUSTOMER = 'INPUT_NUM_OF_CUSTOMER'
export const INPUT_NUM_OF_ADULT = 'INPUT_NUM_OF_ADULT'
export const INPUT_NUM_OF_CHILD = 'INPUT_NUM_OF_CHILD'
export const SELECT_DRINK = 'SELECT_DRINK'
export const RECORD_PRICE = 'RECORD_PRICE'
export const CLEAR_FORM = 'CLEAR_FORM'

export const VALID_PHONE_NUMBER = 'VALID_PHONE_NUMBER'
export const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER'

export const INVALID_NAME = 'INVALID_NAME'
export const VALID_NAME = 'VALID_NAME'

// Table Layout
export const FETCHING_TABLE = 'FETCHING_TABLE'
export const FETCHING_TABLE_SUCCESS = 'FETCHING_TABLE_SUCCESS'
export const FETCHING_TABLE_FAILURE = 'FETCHING_TABLE_FAILURE'
export const SET_TABLE_DETAIL_STATE = 'SET_TABLE_DETAIL_STATE'

//Data History
export const FETCHING_DATA_HISTORY = 'FETCHING_DATA_HISTORY'
export const FETCHING_DATA_HISTORY_SUCCESS = 'FETCHING_DATA_HISTORY_SUCCESS'
export const FETCHING_DATA_HISTORY_FAILURE = 'FETCHING_DATA_HISTORY_FAILURE'
export const NO_DATA_HISTORY = 'NO_DATA_HISTORY'

//Edit Booking
export const EDIT_NUM_OF_CUSTOMER = 'EDIT_NUM_OF_CUSTOMER'
export const UP_NUM_OF_CUSTOMER = 'UP_NUM_OF_CUSTOMER'
export const DOWN_NUM_OF_CUSTOMER = 'DOWN_NUM_OF_CUSTOMER'
export const EDIT_DRINK = 'EDIT_DRINK'

export const VALID_EDIT_NAME = 'VALID_EDIT_NAME'
export const INVALID_EDIT_NAME = 'INVALID_EDIT_NAME'

export const VALID_EDIT_PHONE_NUMBER = 'VALID_EDIT_PHONE_NUMBER'
export const INVALID_EDIT_PHONE_NUMBER = 'INVALID_EDIT_PHONE_NUMBER'



