// CustomerBookingBoard
export const FETCHING_BOOKING_LIST = 'FETCHING_BOOKING_LIST'
export const FETCHING_BOOKING_LIST_SUCCESS = 'FETCHING_BOOKING_LIST_SUCCESS'
export const FETCHING_BOOKING_LIST_FAILURE = 'FETCHING_BOOKING_LIST_FAILURE'
export const NO_BOOKING_LIST = 'NO_BOOKING_LIST'
export const FETCHING_ARRIVING_LIST_SUCCESS = 'FETCHING_ARRIVING_LIST_SUCCESS'
export const NO_ARRIVING_LIST = 'NO_ARRIVING_LIST'
export const FETCHING_EATING_LIST_SUCCESS = 'FETCHING_EATING_LIST_SUCCESS'
export const NO_EATING_LIST = 'NO_EATING_LIST'
export const FETCHING_FINISHING_LIST_SUCCESS = 'FETCHING_FINISHING_LIST_SUCCESS'
export const NO_FINISHING_LIST = 'NO_FINISHING_LIST'

export const MOVE_TO_ARRIVING = 'MOVE_TO_ARRIVING'
export const MOVE_TO_EATING = 'MOVE_TO_EATING'
export const MOVE_TO_FINISHING = 'MOVE_TO_FINISHING'

export const SET_BOOKING_DETAIL_STATE = 'SET_BOOKING_DETAIL_STATE'

// Restaurant Detail
export const FETCHING_RESTAURANT = 'FETCHING_RESTAURANT'
export const FETCHING_RESTAURANT_SUCCESS = 'FETCHING_RESTAURANT_SUCCESS'
export const FETCHING_RESTAURANT_FAILURE = 'FETCHING_RESTAURANT_FAILURE'
export const NO_RESTAURNAT_DATA = 'NO_RESTAURNAT_DATA'

// Add Booking
export const INPUT_NAME = 'INPUT_NAME'
export const INPUT_PHONE_NUMBER = 'INPUT_PHONE_NUMBER'
export const INPUT_TIME = 'INPUT_TIME'
export const INPUT_NUM_OF_CUSTOMER = 'INPUT_NUM_OF_CUSTOMER'
export const INPUT_NUM_OF_ADULT = 'INPUT_NUM_OF_ADULT'
export const INPUT_NUM_OF_CHILD = 'INPUT_NUM_OF_CHILD'
export const SELECT_DRINK = 'SELECT_DRINK'
export const RECORD_PRICE = 'RECORD_PRICE'

